In [2]:
import pandas as pd
from chembl_webresource_client.new_client import new_client

In [4]:
# Target search for coronavirus
target = new_client.target
target_query = target.search('Matrix metalloproteinase-12 homo sapiens')
targets = pd.DataFrame.from_dict(target_query)
targets

,cross_references,organism,pref_name,score,species_group_flag,target_chembl_id,target_components,target_type,tax_id
0,[],Homo sapiens,Homo sapiens,37.0,False,CHEMBL372,[],ORGANISM,9606
1,[],Canis familiaris,Matrix metalloproteinase-12,35.0,False,CHEMBL1932900,"[{'accession': 'A9X4R8', 'component_descriptio...",SINGLE PROTEIN,9615
2,[],Rattus norvegicus,Macrophage metalloelastase,32.0,False,CHEMBL5506,"[{'accession': 'Q63341', 'component_descriptio...",SINGLE PROTEIN,10116
3,[],Oryctolagus cuniculus,Macrophage metalloelastase,32.0,False,CHEMBL1932899,"[{'accession': 'P79227', 'component_descriptio...",SINGLE PROTEIN,9986
4,[],Mus musculus,Macrophage metalloelastase,31.0,False,CHEMBL2594,"[{'accession': 'P34960', 'component_descriptio...",SINGLE PROTEIN,10090
...,...,...,...,...,...,...,...,...,...
337,[],Homo sapiens,Mitochondrial complex I (NADH dehydrogenase),0.0,False,CHEMBL2363065,"[{'accession': 'P03923', 'component_descriptio...",PROTEIN COMPLEX,9606
338,[],Homo sapiens,26S proteasome,0.0,False,CHEMBL2364701,"[{'accession': 'Q99460', 'component_descriptio...",PROTEIN COMPLEX,9606
339,[],Homo sapiens,20S proteasome,0.0,False,CHEMBL3831201,"[{'accession': 'P49721', 'component_descriptio...",PROTEIN COMPLEX GROUP,9606
340,[],Homo sapiens,80S Ribosome,0.0,False,CHEMBL3987582,"[{'accession': 'P08865', 'component_descriptio...",PROTEIN NUCLEIC-ACID COMPLEX,9606
341,[],Homo sapiens,Cytochrome P450,0.0,False,CHEMBL4523986,"[{'accession': 'P08684', 'component_descriptio...",PROTEIN FAMILY,9606

In [5]:
selected_target = targets.target_chembl_id[5]
selected_target

'CHEMBL4393'

In [6]:
activity = new_client.activity
res = activity.filter(target_chembl_id=selected_target).filter(standard_type="IC50")
df = pd.DataFrame.from_dict(res)
df.head(3)

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,Not Determined,115929,[],CHEMBL716818,Inhibition of human Matrix metalloprotease-12,B,None,None,BAO_0000190,...,Homo sapiens,Macrophage metalloelastase,9606,None,None,IC50,uM,UO_0000065,None,None
1,None,None,120889,[],CHEMBL716818,Inhibition of human Matrix metalloprotease-12,B,None,None,BAO_0000190,...,Homo sapiens,Macrophage metalloelastase,9606,None,None,IC50,uM,UO_0000065,None,0.042
2,None,None,122085,[],CHEMBL716818,Inhibition of human Matrix metalloprotease-12,B,None,None,BAO_0000190,...,Homo sapiens,Macrophage metalloelastase,9606,None,None,IC50,uM,UO_0000065,None,0.012

In [8]:
df.to_csv('bioactivity_data.csv', index=False)

In [9]:
df2 = df[df.standard_value.notna()]
df2

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
1,None,None,120889,[],CHEMBL716818,Inhibition of human Matrix metalloprotease-12,B,None,None,BAO_0000190,...,Homo sapiens,Macrophage metalloelastase,9606,None,None,IC50,uM,UO_0000065,None,0.042
2,None,None,122085,[],CHEMBL716818,Inhibition of human Matrix metalloprotease-12,B,None,None,BAO_0000190,...,Homo sapiens,Macrophage metalloelastase,9606,None,None,IC50,uM,UO_0000065,None,0.012
3,None,None,124613,[],CHEMBL716818,Inhibition of human Matrix metalloprotease-12,B,None,None,BAO_0000190,...,Homo sapiens,Macrophage metalloelastase,9606,None,None,IC50,uM,UO_0000065,None,0.009
4,None,None,129779,[],CHEMBL716818,Inhibition of human Matrix metalloprotease-12,B,None,None,BAO_0000190,...,Homo sapiens,Macrophage metalloelastase,9606,None,None,IC50,uM,UO_0000065,None,0.014
5,None,None,143225,[],CHEMBL716818,Inhibition of human Matrix metalloprotease-12,B,None,None,BAO_0000190,...,Homo sapiens,Macrophage metalloelastase,9606,None,None,IC50,uM,UO_0000065,None,0.013
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
730,None,1285833,29023751,[],CHEMBL5739420,MMP Inhibitory Assay: The inhibitory effect of...,B,None,None,BAO_0000190,...,Homo sapiens,Macrophage metalloelastase,9606,None,None,IC50,nM,UO_0000065,None,1.0
731,None,1285834,29023754,[],CHEMBL5739420,MMP Inhibitory Assay: The inhibitory effect of...,B,None,None,BAO_0000190,...,Homo sapiens,Macrophage metalloelastase,9606,None,None,IC50,nM,UO_0000065,None,1.0
732,None,1285835,29023757,[],CHEMBL5739420,MMP Inhibitory Assay: The inhibitory effect of...,B,None,None,BAO_0000190,...,Homo sapiens,Macrophage metalloelastase,9606,None,None,IC50,nM,UO_0000065,None,1.0
733,None,1285836,29023760,[],CHEMBL5739420,MMP Inhibitory Assay: The inhibitory effect of...,B,None,None,BAO_0000190,...,Homo sapiens,Macrophage metalloelastase,9606,None,None,IC50,nM,UO_0000065,None,1.0
734,None,1285837,29023763,[],CHEMBL5739420,MMP Inhibitory Assay: The inhibitory effect of...,B,None,None,BAO_0000190,...,Homo sapiens,Macrophage metalloelastase,9606,None,None,IC50,nM,UO_0000065,None,1.0

In [10]:
bioactivity_class = []
for i in df2.standard_value:
  if float(i) >= 10000:
    bioactivity_class.append("inactive")
  elif float(i) <= 1000:
    bioactivity_class.append("active")
  else:
    bioactivity_class.append("intermediate")

In [11]:
mol_cid = []
for i in df2.molecule_chembl_id:
  mol_cid.append(i)

In [12]:
canonical_smiles = []
for i in df2.canonical_smiles:
  canonical_smiles.append(i)

In [13]:
standard_value = []
for i in df2.standard_value:
  standard_value.append(i)

In [14]:
data_tuples = list(zip(mol_cid, canonical_smiles, bioactivity_class, standard_value))
df3 = pd.DataFrame( data_tuples,  columns=['molecule_chembl_id', 'canonical_smiles', 'bioactivity_class', 'standard_value'])
df3

,molecule_chembl_id,canonical_smiles,bioactivity_class,standard_value
0,CHEMBL1788203,CCCC[C@H](CC(=O)NO)S(=O)(=O)c1ccccc1,active,42.0
1,CHEMBL263501,CCCCC(CC(=O)NO)S(=O)(=O)c1ccccc1,active,12.0
2,CHEMBL2092878,CCCC[C@@H](CC(=O)NO)S(=O)(=O)c1ccccc1,active,9.0
3,CHEMBL77258,CCCCC(CC(=O)NO)S(=O)(=O)C1CCCCC1,active,14.0
4,CHEMBL78001,CCCCC(CC(=O)NO)S(=O)(=O)c1ccc2ccccc2c1,active,13.0
...,...,...,...,...
686,CHEMBL5742512,CCC1(c2cnccc2Sc2ccc(/C=C/c3ccnc(C)c3)cc2)NC(=O...,active,1.0
687,CHEMBL5800908,Cc1cc(C#Cc2ccc(Sc3ccsc3C3NC(=O)NC3=O)cc2)ccn1,active,1.0
688,CHEMBL6006240,Cc1cc(/C=C/c2ccc(Sc3ccsc3C3NC(=O)NC3=O)cc2)ccn1,active,1.0
689,CHEMBL5761540,Cc1cc(C#Cc2ccc(Sc3cnn(C)c3C3NC(=O)NC3=O)cc2)ccn1,active,1.0
690,CHEMBL6013997,Cc1cc(/C=C/c2ccc(Sc3cnn(C)c3C3NC(=O)NC3=O)cc2)...,active,1.0

In [15]:
pd.concat([df3,pd.Series(bioactivity_class)], axis=1)

,molecule_chembl_id,canonical_smiles,bioactivity_class,standard_value,0
0,CHEMBL1788203,CCCC[C@H](CC(=O)NO)S(=O)(=O)c1ccccc1,active,42.0,active
1,CHEMBL263501,CCCCC(CC(=O)NO)S(=O)(=O)c1ccccc1,active,12.0,active
2,CHEMBL2092878,CCCC[C@@H](CC(=O)NO)S(=O)(=O)c1ccccc1,active,9.0,active
3,CHEMBL77258,CCCCC(CC(=O)NO)S(=O)(=O)C1CCCCC1,active,14.0,active
4,CHEMBL78001,CCCCC(CC(=O)NO)S(=O)(=O)c1ccc2ccccc2c1,active,13.0,active
...,...,...,...,...,...
686,CHEMBL5742512,CCC1(c2cnccc2Sc2ccc(/C=C/c3ccnc(C)c3)cc2)NC(=O...,active,1.0,active
687,CHEMBL5800908,Cc1cc(C#Cc2ccc(Sc3ccsc3C3NC(=O)NC3=O)cc2)ccn1,active,1.0,active
688,CHEMBL6006240,Cc1cc(/C=C/c2ccc(Sc3ccsc3C3NC(=O)NC3=O)cc2)ccn1,active,1.0,active
689,CHEMBL5761540,Cc1cc(C#Cc2ccc(Sc3cnn(C)c3C3NC(=O)NC3=O)cc2)ccn1,active,1.0,active
690,CHEMBL6013997,Cc1cc(/C=C/c2ccc(Sc3cnn(C)c3C3NC(=O)NC3=O)cc2)...,active,1.0,active

In [ ]:
df3.to_csv('bioactivity_preprocessed_data.csv', index=False)

'ls' is not recognized as an internal or external command,
operable program or batch file.